const bar = document.createElement("div");
bar.id = "my-extension-bar";
bar.textContent = "c00lkidd has hacked your g00gle... results generated by artificial intelligence will no longer appear";

Object.assign(bar.style, {
  position: "fixed",
  top: "0",
  left: "0",
  width: "100%",
  height: "25px",
  backgroundColor: "black",
  color: "white",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: "20px",
  fontFamily: "sans-serif",
  zIndex: "999999"
});

const hideButtons = () => {
  document.querySelectorAll('button[jsname="B6rgad"]').forEach(aiMode => aiMode.remove());
  document.querySelectorAll('button[jsname="hGDJR"]').forEach(aiSearch => aiSearch.remove());
  document.querySelectorAll('button[jsname="En3Upb"]').forEach(bananaPro => bananaPro.remove());
  document.querySelector('div[class="Bk6bBe"]')?.remove();
  document.querySelector('a[class="XVMlrc C6AK7c"]')?.remove();
  document.querySelector('div[class="YNk70c EjQTId"]')?.remove();
  document.querySelector('div[data-hveid="CAgQBg"]')?.remove();
  document.querySelector('div[id="Odp5De"]')?.remove();
  document.querySelector('div[class="ULSxyf"]')?.remove();
};

const svg = document.querySelector('svg.lnXdpd');

if (svg) {
  const img = document.createElement("img");
  img.src = browser.runtime.getURL("icons/team_cool_kidd.png");
  img.alt = "zuhn's favorite word";
  img.style.height = svg.getBoundingClientRect().height + "px";
  img.style.width = "auto";

  svg.replaceWith(img);
}

hideButtons();
const observer = new MutationObserver(hideButtons);
observer.observe(document.body, { childList: true, subtree: true });

// const logo = document.querySelector('img[]')

document.body.prepend(bar);
document.body.style.marginTop = "40px";

